import "./globals.css";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import Link from "next/link";
import Provider from "@/lib/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Pokemon Next App",
  description: "Generated by create next app",
};

// 1. Переделать фетчи под query
// 2. Расширить [pokemon]
// 3. Добавить навигацию
// (4. Сделать pagination если кол-во покемонов больше чем 50)

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex  flex-col items-center gap-5 m-auto my-auto mt-5">
          <div className="z-10 items-center justify-center text-sm  ">
            <Link href="/">
              <h2 className="text-2xl text-bold ">Pokemon Next App</h2>
            </Link>
          </div>
          <Provider>{children}</Provider>
        </main>
      </body>
    </html>
  );
}
